
upstream isucondition {
	server unix:/tmp/isucondition.sock;
}

server {
    listen 443 ssl http2;

    ssl_certificate /etc/nginx/certificates/tls-cert.pem;
    ssl_certificate_key /etc/nginx/certificates/tls-key.pem;


    root /home/isucon/webapp/public;

    location = /favicon.ico {
        alias /home/isucon/webapp/public/assets/favicon.d0f5f504.svg;
        access_log off;
    }

    location /assets/ {
        alias /home/isucon/webapp/public/assets/;

        expires 1y;
        add_header Cache-Control "public, immutable";
	access_log off;
    }

    location /internal-icons/ {
	internal;
    	alias /home/isucon/webapp/icons/;

        expires 1y;
        add_header Cache-Control "public, immutable";
        access_log off;
    }

    location = / {
      try_files /index.html =404;
      add_header Cache-Control "no-cache";
      access_log off;
    }


    location = /register {
      try_files /index.html =404;
      add_header Cache-Control "no-cache";
      access_log off;
    }

    location ~ ^/isu/[^/]+/?$ {
      try_files /index.html =404;
      add_header Cache-Control "no-cache";
      access_log off;
    }

    location ~ ^/isu/[^/]+/(condition|graph)/?$ {
      try_files /index.html =404;
      add_header Cache-Control "no-cache";
      access_log off;
    }
    
    location /api/ {
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_pass http://isucondition;
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;          
        proxy_pass http://isucondition;
    }
}
